FROM ericsage/studio

# Installs the latest version of OCaml

# Install the latest version of OCaml using opam
RUN wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
